name: 'check-if-base-image-updated'
outputs:
  result:
    description: 'is-base-image-updated [true, false]'
    value: ${{ steps.result-step.outputs.result }}
runs:
  using: 'composite'
  steps:
    - id: result-step
      run: echo "::set-output name=result::true"
      shell: bash