name: 'check-if-base-image-updated'
inputs:
  package-link:
    required: true
outputs:
  result:
    description: 'is-base-image-updated [true, false]'
    value: ${{ steps.result-step.outputs.result }}
runs:
  using: 'composite'
  steps:
    - id: result-step
      env:
        package_link: ${{ inputs.package-link }}
      run: python3 ${{ github.action_path }}/run.py Dockerfile"
      shell: bash