name: 'build and push docker image'
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '3/5 * * * *'

# check if base image updated
# check if package updated [ apk update ; apk -u list ] not empty

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      package_repo: ghcr.io/${{ github.repository_owner }}/github_actions_demo
    steps:
      - id: get-time
        run: |
          tp=$(date -u +'%Y%m%d_%H%M%S')
          echo "::set-output name=build-time::$tp"
          echo Timestamp: $tp

      - name: Checkout Repo
        uses: actions/checkout@v2

      - id: check-if-base-image-updated
        if: ${{ github.event_name == 'schedule' }}
        name: check-if-base-image-updated
        uses: ./.github/actions/check-if-base-image-updated
        with:
          package-tag: ${{ env.package_repo }}:latest

      - run: |
          echo steps.check-if-base-image-updated.outputs.result = ${{ steps.check-if-base-image-updated.outputs.result }}

      - if: ${{ steps.check-if-base-image-updated.outcome == 'skipped' || steps.check-if-base-image-updated.outputs.result != '0' }}
        name: Do build and push
        uses: ./.github/actions/build-and-push
        with:
            package-version: ${{ steps.get-time.outputs.build-time }}