name: 'build and push docker image'
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '45 * * * *'

# check if base image updated
# check if package updated [ apk update ; apk -u list ] not empty

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v2
      -
        name: check-if-base-image-updated
        id: check-if-base-image-updated
        uses: ./.github/actions/check-if-base-image-updated
      -
        run: |
          echo steps.check-if-base-image-updated.outputs.result = ${{ steps.check-if-base-image-updated.outputs.result }}
#      -
#        name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          platforms: linux/amd64
#          push: true
#          tags: |
#            ghcr.io/${{ github.repository_owner }}/github_actions_demo:latest
#            ghcr.io/${{ github.repository_owner }}/github_actions_demo:1.0.0