name: every 5 mins
on:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  List-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
          echo run schedule "'${{ github.event.schedule }}'"
      - run: echo "🍏 This job's status is ${{ job.status }}."